// ===================================================
//  BenBooks – Dữ liệu sách mẫu (data.js)
// ===================================================

const BOOKS = [

  {
    id: 13,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành tiếp diễn (Past Perfect Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1205,
    editions: 10,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/26/image-20260326114914102.png",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 14,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành tiếp diễn (Future Perfect Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1540,
    editions: 12,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Audio Book",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325090916895.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 15,
    title: "Kiến thức Tiếng Anh trọng tâm: Danh từ đếm được, Danh từ không đếm được (Countable Nouns & Uncountable Nouns)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.8,
    views: 3200,
    editions: 34,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325082812609.png",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 16,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai gần (Near Future Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "5.000 đ",
    rating: 4.2,
    views: 900,
    editions: 8,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Audio Book",
    pages: 100,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162808613.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 17,
    title: "Kiến thức Tiếng Anh trọng tâm Động từ nguyên mẫu (To verb)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1100,
    editions: 9,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 110,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162838695.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 18,
    title: "Toán tư duy tiền tiểu học",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5600,
    editions: 120,
    categories: ["Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "20x20 cm",
    bookType: "Audio Book",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319120355074.jpg",
    description: "Giúp trẻ phát triển tư duy từ sớm.",
    chapters: [],
    comments: []
  },
  {
    id: 19,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại hoàn thành (Present Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.7,
    views: 4500,
    editions: 42,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 160,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316123652646.png",
    description: "Tài liệu ôn luyện chuyên sâu.",
    chapters: [],
    comments: []
  },
  {
    id: 20,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành (Future Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "5.000 đ",
    rating: 4.3,
    views: 1250,
    editions: 14,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Audio Book",
    pages: 115,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316153417345.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 21,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành (Past Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1800,
    editions: 18,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 125,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/13/image-20260313162537925.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 22,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai đơn (Simple Future Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "20.000 đ",
    rating: 4.8,
    views: 5400,
    editions: 60,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Audio Book",
    pages: 140,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/10/image-20260310151314926.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 23,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai tiếp diễn (Future Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.1,
    views: 750,
    editions: 5,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 105,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/7/image-20260307100233319.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 24,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ tiếp diễn (Past Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: false,
    price: "20.000 đ",
    rating: 4.6,
    views: 3100,
    editions: 28,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Audio Book",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306083737170.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 25,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ đơn (Past Simple Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.9,
    views: 8200,
    editions: 95,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 160,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306085422183.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 26,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại tiếp diễn (Present Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 4500,
    editions: 33,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 135,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306141601047.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 27,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại đơn (Present Simple Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 12000,
    editions: 154,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/5/image-20260305102435472.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 28,
    title: "Cuộc phiêu lưu của chú Kiến Vàng",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "10.455 đ",
    rating: 4.7,
    views: 3100,
    editions: 26,
    categories: ["Sách Thiếu nhi"],
    genre: "Truyện tranh",
    yearPublished: 2026,
    size: "15x21 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227144734328.jpg",
    description: "Truyện kể cho bé.",
    chapters: [],
    comments: []
  },
  {
    id: 29,
    title: "Kiến thức Tiếng Anh trọng tâm: Tính từ miêu tả (Descriptive Adjective)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.3,
    views: 1800,
    editions: 15,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 110,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227091856276.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 30,
    title: "Cẩm nang ôn thi tốt nghiệp tin học, chuyên đề về website HTML (tập 1)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 2900,
    editions: 31,
    categories: ["Sách tham khảo", "Giáo dục", "Công nghệ thông tin"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 200,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090637354.png",
    description: "Tài liệu chuyên sâu ngành lập trình web.",
    chapters: [],
    comments: []
  },
  {
    id: 31,
    title: "Cẩm nang ôn thi tốt nghiệp tin học chuyên đề về Website: CSS (tập 1)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3300,
    editions: 38,
    categories: ["Sách tham khảo", "Giáo dục", "Công nghệ thông tin"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 220,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090956096.png",
    description: "Tài liệu chuyên môn hữu ích.",
    chapters: [],
    comments: []
  },
  {
    id: 32,
    title: "Những vĩ nhân trong lịch sử: Ernest Hemingway",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 15400,
    editions: 205,
    categories: ["Tiểu sử - Hồi ký"],
    genre: "Kiến thức chung",
    yearPublished: 2025,
    size: "13x20 cm",
    bookType: "Ebook",
    pages: 350,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/11/27/image-book-20251127081656947.png",
    description: "Câu chuyện về cuộc đời của nhà văn vĩ đại.",
    chapters: [],
    comments: []
  },
  {
    id: 33,
    title: "Phương tiện giao thông quanh ta",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 1250,
    editions: 15,
    categories: ["Sách thiếu nhi", "Giáo dục"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/11/image-book-20250811140652361.jpg",
    description: "Sách giúp bé tìm hiểu phương tiện giao thông.",
    chapters: [],
    comments: []
  },
  {
    id: 34,
    title: "Việt Nam muôn màu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 3400,
    editions: 22,
    categories: ["Sách thiếu nhi", "Văn hóa"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 60,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100405005.jpg",
    description: "Giới thiệu văn hóa Việt Nam.",
    chapters: [],
    comments: []
  },
  {
    id: 35,
    title: "Nghề nghiệp tương lai: Logistics - cung ứng",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 1800,
    editions: 12,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094800703.jpg",
    description: "Tìm hiểu ngành logistics.",
    chapters: [],
    comments: []
  },
  {
    id: 36,
    title: "Nghề nghiệp tương lai: Du lịch",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 2200,
    editions: 18,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094442151.jpg",
    description: "Tìm hiểu ngành du lịch.",
    chapters: [],
    comments: []
  },
  {
    id: 37,
    title: "Nghề nghiệp tương lai: Tài nguyên môi trường",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1500,
    editions: 10,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095249548.jpg",
    description: "Tìm hiểu ngành môi trường.",
    chapters: [],
    comments: []
  },
  {
    id: 38,
    title: "Tết thiếu nhi",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5600,
    editions: 40,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 40,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095939163.jpg",
    description: "Khám phá tết thiếu nhi.",
    chapters: [],
    comments: []
  },
  {
    id: 39,
    title: "Nghề nghiệp tương lai: Nông nghiệp công nghệ cao",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1300,
    editions: 11,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-2025070409491636.jpg",
    description: "Tìm hiểu ngành nông nghiệp CNC.",
    chapters: [],
    comments: []
  },
  {
    id: 40,
    title: "Tết Trung thu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 6500,
    editions: 45,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 45,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100127787.jpg",
    description: "Khám phá trăng rằm.",
    chapters: [],
    comments: []
  },
  {
    id: 41,
    title: "Khám phá Quốc kì",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 3100,
    editions: 20,
    categories: ["Giáo dục"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 60,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704093255109.jpg",
    description: "Nhận biết cờ các nước.",
    chapters: [],
    comments: []
  },
  {
    id: 42,
    title: "Nghề nghiệp tương lai: Phân tích dữ liệu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 4500,
    editions: 33,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 100,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095029845.jpg",
    description: "Tìm hiểu ngành Data.",
    chapters: [],
    comments: []
  },
  {
    id: 43,
    title: "Tết Nguyên đán",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 8000,
    editions: 55,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095744719.jpg",
    description: "Khám phá tết cổ truyền.",
    chapters: [],
    comments: []
  },
  {
    id: 44,
    title: "Lạc quanh thế giới: Lạc khám phá Nam Mỹ bí ẩn",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4100,
    editions: 22,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/8/image-book-20250808083006201.png",
    description: "Hành trình đến Nam Mỹ.",
    chapters: [],
    comments: []
  },
  {
    id: 45,
    title: "Lạc quanh thế giới: Lạc tới Thổ Nhĩ Kỳ cổ kính",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 3200,
    editions: 18,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320100948394.png",
    description: "Khám phá vùng đất giao thoa.",
    chapters: [],
    comments: []
  },
  {
    id: 46,
    title: "Lạc quanh thế giới: Lạc tới New Zealand và Australia",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3800,
    editions: 21,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101301424.png",
    description: "Khám phá châu Đại Dương.",
    chapters: [],
    comments: []
  },
  {
    id: 47,
    title: "Lạc quanh thế giới: Lạc tới nước Ý mộng mơ",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5200,
    editions: 30,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-2025032009163242.png",
    description: "Lang thang ở kinh đô nghệ thuật.",
    chapters: [],
    comments: []
  },
  {
    id: 48,
    title: "Lạc quanh thế giới: Lạc vào Ai Cập huyền bí",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4700,
    editions: 25,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101739797.png",
    description: "Bí ẩn lăng mộ Pharaoh.",
    chapters: [],
    comments: []
  },
  {
    id: 49,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Ai là người phát hiện ra tia X",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 2900,
    editions: 14,
    categories: ["Khoa học"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317142940692.png",
    description: "Khám phá khoa học quanh ta.",
    chapters: [],
    comments: []
  },
  {
    id: 50,
    title: "Tìm hiểu các trường Đại học ở Việt Nam: Đại học Bách khoa Hà Nội",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 7500,
    editions: 60,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/5/12/image-book-20250512094945531.png",
    description: "Tài liệu luyện thi và tìm hiểu.",
    chapters: [],
    comments: []
  },
  {
    id: 51,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Chiếc máy ảnh đầu tiên trên thế giới ra đời như thế nào?",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3100,
    editions: 19,
    categories: ["Khoa học"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317140914719.png",
    description: "Lịch sử công nghệ.",
    chapters: [],
    comments: []
  },
  {
    id: 52,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Tàu Parker và hành trình vượt không gian khám phá vũ trụ",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4200,
    editions: 25,
    categories: ["Khoa học", "Vũ trụ"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317133017076.png",
    description: "Hành trình ra ngoài không gian.",
    chapters: [],
    comments: []
  },
  {
    id: 53,
    title: "Phân tích kiến thức cơ bản trong các văn bản",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "6.715 đ",
    rating: 5,
    views: 2100,
    editions: 17,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 130,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/9/3/image-book-20250903105050594.jpg",
    description: "Tài liệu phân tích kiến thức cơ bản trong các văn bản Ngữ văn.",
    chapters: [],
    comments: []
  },
  {
    id: 54,
    title: "Hoạt động giáo dục ngoài giờ lên lớp 6",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "25.000 đ",
    rating: 5,
    views: 3400,
    editions: 28,
    categories: ["Giáo dục"],
    genre: "Giáo dục",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 160,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/9/4/image-book-20250904152208067.jpg",
    description: "Tài liệu hỗ trợ hoạt động giáo dục ngoài giờ lên lớp dành cho học sinh lớp 6.",
    chapters: [],
    comments: []
  },
  {
    id: 55,
    title: "Rửa tay cho sạch nào",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 5,
    views: 4800,
    editions: 52,
    categories: ["Sách Thiếu nhi", "Sức khoẻ"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 32,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-20250826112045728.jpg",
    description: "Sách tranh hướng dẫn bé cách rửa tay đúng cách để bảo vệ sức khoẻ.",
    chapters: [],
    comments: []
  },
  {
    id: 56,
    title: "Đề kiểm tra Toán lớp 6 tập 1",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 5,
    views: 5200,
    editions: 44,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/22/image-book-20250822103655323.jpg",
    description: "Tuyển tập đề kiểm tra Toán lớp 6, giúp ôn luyện hiệu quả.",
    chapters: [],
    comments: []
  },
  {
    id: 57,
    title: "Để học tốt Tiếng Việt 3 tập 2",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 5,
    views: 6100,
    editions: 58,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 140,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-20250826111445887.png",
    description: "Tài liệu hỗ trợ học tốt Tiếng Việt lớp 3 tập 2.",
    chapters: [],
    comments: []
  },
  {
    id: 58,
    title: "Bộ câu hỏi trắc nghiệm đúng sai Toán 12",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "25.000 đ",
    rating: 5,
    views: 8900,
    editions: 76,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 200,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/9/3/image-book-20250903104126205.jpg",
    description: "Bộ câu hỏi trắc nghiệm đúng sai Toán 12 theo chương trình mới.",
    chapters: [],
    comments: []
  },
  {
    id: 59,
    title: "Chinh phục các bài Toán khó lớp 8",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "25.000 đ",
    rating: 5,
    views: 7300,
    editions: 62,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 180,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-2025082611374253.jpg",
    description: "Chinh phục các bài toán khó lớp 8, bồi dưỡng học sinh giỏi.",
    chapters: [],
    comments: []
  },
  {
    id: 60,
    title: "Để học tốt Ngữ văn 12 tập 2",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "25.000 đ",
    rating: 5,
    views: 9500,
    editions: 88,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 250,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/9/4/image-book-20250904144722442.jpg",
    description: "Hướng dẫn học tốt Ngữ văn 12 tập 2, ôn thi tốt nghiệp THPT.",
    chapters: [],
    comments: []
  },
  {
    id: 61,
    title: "Văn tự sự, miêu tả",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "6.400 đ",
    rating: 5,
    views: 3600,
    editions: 31,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 110,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-2025082611242307.jpg",
    description: "Hướng dẫn viết văn tự sự và miêu tả hiệu quả cho học sinh.",
    chapters: [],
    comments: []
  },
  {
    id: 62,
    title: "Thế giới quanh em",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 5,
    views: 5400,
    editions: 46,
    categories: ["Sách Thiếu nhi", "Khoa học"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 60,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/18/image-book-20250818101232634.jpg",
    description: "Khám phá thế giới xung quanh em qua góc nhìn khoa học thú vị.",
    chapters: [],
    comments: []
  }
];

// Categories for sidebar
const CATEGORIES = [
  {
    title: "DANH MỤC SÁCH CỦA BẠN",
    items: [
      { name: "Sách tham khảo và bồi dưỡng nâng cao", children: ["Sách tham khảo theo môn học", "Sách luyện thi và ôn tập", "Sách bồi dưỡng học sinh giỏi"] },
      { name: "Sách khoa học và kỹ năng sống", children: ["Sách khoa học phổ thông", "Sách kỹ năng sống và giáo dục đạo đức"] },
      { name: "Sách văn học và nghệ thuật", children: ["Văn học Việt Nam", "Văn học nước ngoài", "Nghệ thuật"] },
      { name: "Sách lịch sử, địa lý và văn hóa", children: ["Lịch sử", "Địa lý", "Văn hóa và xã hội"] },
      { name: "Sách ngoại ngữ", children: ["Tiếng Anh", "Các ngoại ngữ khác"] }
    ]
  },
  {
    title: "PHÂN LOẠI THEO BỘ SÁCH",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  }
];

const TOPICS = [
  "Truyện cổ tích",
  "Tác phẩm kinh điển",
  "Văn học thiếu nhi",
  "Truyện tranh Nhật Bản",
  "Chăm sóc sức khoẻ trẻ em",
  "Kinh tế - Chính trị - Xã hội",
  "Tâm lý học"
];

const AUTHORS_LIST = [
  "Nguyễn Nhật Ánh",
  "Phan Thị Vàng Anh",
  "Trần Tùng Chinh",
  "Nguyễn Văn Anh",
  "Hoàng Liên",
  "Xuân Quỳnh",
  "Nguyễn Mỹ Nữ"
];

const LANGUAGES = ["Tiếng Việt", "Tiếng Anh", "Tiếng Trung"];
