// ===================================================
//  BenBooks – Dữ liệu sách mẫu (data.js)
// ===================================================

const BOOKS = [
  {
    id: 1,
    title: "Tủ sách Tuổi Thần tiên - Nhạc sĩ đường phố",
    subtitle: "Subtitle title",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.5,
    views: 30209,
    editions: 116,
    categories: ["Sách Thiếu nhi", "Minh hoạ", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook, xã hội hoá",
    pages: 212,
    language: "Tiếng Việt",
    isbn: "978-604-0-58612-6",
    maISBN: "970-604-02-58012-6",
    coverColor: "#E8D4A0",
    description: `Là một cuốn sách truyện tranh vô cùng tuyệt vời dành cho các em nhỏ. Câu chuyện kể về một cậu bé có đam mê với âm nhạc, đặc biệt là violin và sáo. Cậu thường xuyên biểu diễn trên những con phố nhỏ, mang niềm vui đến cho mọi người qua những giai điệu tuyệt vời.

Một ngày nọ, cậu bé gặp được một nhạc sĩ già tài ba. Ông đã dạy cho cậu nhiều bài học quý giá không chỉ về âm nhạc mà còn về cuộc sống. Từ đó, cậu bé không chỉ trở thành một nhạc sĩ giỏi hơn mà còn hiểu được ý nghĩa thực sự của nghệ thuật.

Cuốn sách được minh hoạ bằng những hình vẽ tuyệt đẹp, sống động, mang đến cho người đọc một trải nghiệm thị giác tuyệt vời cùng với nội dung câu chuyện ý nghĩa.`,
    chapters: ["Chương 1: Cậu bé và cây violin", "Chương 2: Giai điệu đường phố", "Chương 3: Người thầy bí ẩn", "Chương 4: Bài học đầu tiên", "Chương 5: Buổi hoà nhạc nhỏ"],
    comments: [
      {
        user: "Thành Luân",
        badge: "CÁN BỘ CNTT",
        time: "28 giờ trước",
        text: "Một cuốn sách rất hay và bổ ích cho các em nhỏ. Hình ảnh rất đẹp và sinh động, nội dung ý nghĩa.",
        reply: { user: "Trả lời", time: "24 giờ trước", text: "" }
      }
    ]
  },
  {
    id: 2,
    title: "Miền cỏ hát",
    subtitle: "",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: true,
    price: null,
    rating: 4.3,
    views: 18540,
    editions: 89,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "14x20 cm",
    bookType: "Sách ebook",
    pages: 156,
    language: "Tiếng Việt",
    isbn: "978-604-1-12345-6",
    maISBN: "",
    coverColor: "#C5D8A0",
    description: "Tuyển tập truyện thiếu nhi về miền quê yên bình với những cánh đồng cỏ xanh mướt.",
    chapters: ["Phần 1", "Phần 2", "Phần 3"],
    comments: []
  },
  {
    id: 3,
    title: "Bầu trời trong quả trứng",
    subtitle: "",
    author: "Xuân Quỳnh",
    authorBooks: 22,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.8,
    views: 42100,
    editions: 205,
    categories: ["Sách Thiếu nhi", "Thơ"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2018,
    size: "13x19 cm",
    bookType: "Sách giấy, ebook",
    pages: 128,
    language: "Tiếng Việt",
    isbn: "978-604-2-23456-7",
    maISBN: "",
    coverColor: "#F0D5A0",
    description: "Tập thơ thiếu nhi kinh điển của nhà thơ Xuân Quỳnh, với những bài thơ trong trẻo, giàu hình ảnh.",
    chapters: ["Bài 1", "Bài 2", "Bài 3"],
    comments: []
  },
  {
    id: 4,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.6,
    views: 25300,
    editions: 134,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 198,
    language: "Tiếng Việt",
    isbn: "978-604-0-67890-1",
    maISBN: "",
    coverColor: "#D0E8F0",
    description: "Câu chuyện phiêu lưu kỳ thú của Ốc Tiêu trong thế giới thần tiên.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  },
  {
    id: 5,
    title: "Rung cảm đầu đời (tặng 2 tấm thiệp)",
    subtitle: "",
    author: "Nguyễn Nhật Ánh",
    authorBooks: 48,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.9,
    views: 56700,
    editions: 310,
    categories: ["Văn học thiếu nhi"],
    genre: "Văn học thiếu nhi",
    yearPublished: 2021,
    size: "13x20 cm",
    bookType: "Sách giấy, ebook",
    pages: 246,
    language: "Tiếng Việt",
    isbn: "978-604-3-45678-9",
    maISBN: "",
    coverColor: "#F5C0C0",
    description: "Tác phẩm mới nhất của Nguyễn Nhật Ánh về những rung cảm tuổi mới lớn.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4", "Chương 5", "Chương 6"],
    comments: []
  },
  {
    id: 6,
    title: "Làm chủ cơn giận",
    subtitle: "Subtitle title",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "311.500đ / Tháng",
    rating: 4.2,
    views: 53158,
    editions: 3039,
    categories: ["Sách Thiếu nhi", "Minh hoạ", "Truyện tranh"],
    genre: "Tác phẩm kinh điển",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook, xã hội hoá",
    pages: 212,
    language: "Tiếng Việt",
    isbn: "978-604-0-58012-6",
    maISBN: "970-604-02-58012-6",
    coverColor: "#FFE0B0",
    description: `Cuốn sách giúp trẻ em hiểu và kiểm soát cảm xúc giận dữ. Thông qua những câu chuyện sinh động và hình ảnh minh hoạ đẹp mắt, cuốn sách dạy trẻ cách nhận biết khi nào mình đang tức giận, tại sao mình tức giận và làm thế nào để xử lý cảm xúc đó một cách tích cực.

Mỗi chương sách đều có bài tập thực hành để trẻ có thể áp dụng ngay vào cuộc sống hàng ngày. Đây là cuốn sách không thể thiếu trong tủ sách của mọi gia đình có con nhỏ.

Sách cũng bao gồm phần hướng dẫn dành cho phụ huynh, giúp cha mẹ hiểu và đồng hành cùng con trong việc quản lý cảm xúc.`,
    chapters: ["Chương 1: Cơn giận là gì?", "Chương 2: Nhận biết cảm xúc", "Chương 3: Kỹ thuật hít thở", "Chương 4: Nói ra nỗi lòng", "Chương 5: Bài tập vui"],
    comments: [
      {
        user: "Thành Luân",
        badge: "CÁN BỘ CNTT",
        time: "28 giờ trước",
        text: "Sách rất hữu ích cho việc giáo dục cảm xúc trẻ em. Hình ảnh đẹp, nội dung phù hợp lứa tuổi.",
        reply: null
      }
    ]
  },
  {
    id: 7,
    title: "Chìm ra rừng hành hạnh phúc",
    subtitle: "",
    author: "Hoàng Liên",
    authorBooks: 8,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "250.000đ / Tháng",
    rating: 4.1,
    views: 12400,
    editions: 67,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "15x21 cm",
    bookType: "Sách ebook",
    pages: 180,
    language: "Tiếng Việt",
    isbn: "978-604-4-56789-0",
    maISBN: "",
    coverColor: "#D8F0D0",
    description: "Hành trình tìm kiếm hạnh phúc trong khu rừng kỳ diệu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3"],
    comments: []
  },
  {
    id: 8,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu (Tập 2)",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.7,
    views: 21000,
    editions: 98,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 210,
    language: "Tiếng Việt",
    isbn: "978-604-0-78901-2",
    maISBN: "",
    coverColor: "#E0D0F0",
    description: "Phần tiếp theo của cuộc phiêu lưu Ốc Tiêu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3"],
    comments: []
  },
  {
    id: 9,
    title: "Làm chủ con giận (tặng 2 tấm thiệp)...",
    subtitle: "",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "195.000đ / Tháng",
    rating: 4.0,
    views: 8900,
    editions: 45,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2021,
    size: "14x20 cm",
    bookType: "Sách ebook",
    pages: 144,
    language: "Tiếng Việt",
    isbn: "978-604-5-89012-3",
    maISBN: "",
    coverColor: "#F0E0C0",
    description: "Tuyển tập bài tập quản lý cảm xúc cho trẻ em.",
    chapters: ["Phần 1", "Phần 2", "Phần 3"],
    comments: []
  },
  {
    id: 10,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu (Tập 3)",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.5,
    views: 19500,
    editions: 87,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2021,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 195,
    language: "Tiếng Việt",
    isbn: "978-604-0-99123-4",
    maISBN: "",
    coverColor: "#C0E0F0",
    description: "Tập 3 của series Thiên thần Ốc Tiêu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  },
  {
    id: 11,
    title: "Bầu trời trong quả trứng (Bản Audio)",
    subtitle: "",
    author: "Xuân Quỳnh",
    authorBooks: 22,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: true,
    price: null,
    rating: 4.6,
    views: 15600,
    editions: 78,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "",
    bookType: "Audiobook",
    pages: 0,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    description: "Phiên bản audio của tập thơ Bầu trời trong quả trứng.",
    chapters: [],
    comments: []
  },
  {
    id: 12,
    title: "Rung cảm đầu đời (tặng 2 tấm thiệp) Tập 2...",
    subtitle: "",
    author: "Nguyễn Nhật Ánh",
    authorBooks: 48,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "280.000đ / Tháng",
    rating: 4.4,
    views: 31200,
    editions: 156,
    categories: ["Văn học thiếu nhi"],
    genre: "Văn học thiếu nhi",
    yearPublished: 2022,
    size: "13x20 cm",
    bookType: "Sách giấy, ebook",
    pages: 268,
    language: "Tiếng Việt",
    isbn: "978-604-3-56789-0",
    maISBN: "",
    coverColor: "#E8C0D0",
    description: "Phần tiếp theo của Rung cảm đầu đời.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  }
];

// Categories for sidebar
const CATEGORIES = [
  {
    title: "DANH MỤC SÁCH CỦA BẠN",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  },
  {
    title: "PHÂN LOẠI THEO BỘ SÁCH",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  }
];

const TOPICS = [
  "Truyện cổ tích",
  "Tác phẩm kinh điển",
  "Văn học thiếu nhi",
  "Truyện tranh Nhật Bản",
  "Chăm sóc sức khoẻ trẻ em",
  "Kinh tế - Chính trị - Xã hội",
  "Tâm lý học"
];

const AUTHORS_LIST = [
  "Nguyễn Nhật Ánh",
  "Phan Thị Vàng Anh",
  "Trần Tùng Chinh",
  "Nguyễn Văn Anh",
  "Hoàng Liên",
  "Xuân Quỳnh",
  "Nguyễn Mỹ Nữ"
];

const LANGUAGES = ["Tiếng Việt", "Tiếng Anh", "Tiếng Trung"];
