// ===================================================
//  BenBooks – Dữ liệu sách mẫu (data.js)
// ===================================================

const BOOKS = [
  {
    id: 1,
    title: "Tủ sách Tuổi Thần tiên - Nhạc sĩ đường phố",
    subtitle: "Subtitle title",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.5,
    views: 30209,
    editions: 116,
    categories: ["Sách Thiếu nhi", "Minh hoạ", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook, xã hội hoá",
    pages: 212,
    language: "Tiếng Việt",
    isbn: "978-604-0-58612-6",
    maISBN: "970-604-02-58012-6",
    coverColor: "#E8D4A0",
    description: `Là một cuốn sách truyện tranh vô cùng tuyệt vời dành cho các em nhỏ. Câu chuyện kể về một cậu bé có đam mê với âm nhạc, đặc biệt là violin và sáo. Cậu thường xuyên biểu diễn trên những con phố nhỏ, mang niềm vui đến cho mọi người qua những giai điệu tuyệt vời.

Một ngày nọ, cậu bé gặp được một nhạc sĩ già tài ba. Ông đã dạy cho cậu nhiều bài học quý giá không chỉ về âm nhạc mà còn về cuộc sống. Từ đó, cậu bé không chỉ trở thành một nhạc sĩ giỏi hơn mà còn hiểu được ý nghĩa thực sự của nghệ thuật.

Cuốn sách được minh hoạ bằng những hình vẽ tuyệt đẹp, sống động, mang đến cho người đọc một trải nghiệm thị giác tuyệt vời cùng với nội dung câu chuyện ý nghĩa.`,
    chapters: ["Chương 1: Cậu bé và cây violin", "Chương 2: Giai điệu đường phố", "Chương 3: Người thầy bí ẩn", "Chương 4: Bài học đầu tiên", "Chương 5: Buổi hoà nhạc nhỏ"],
    comments: [
      {
        user: "Thành Luân",
        badge: "CÁN BỘ CNTT",
        time: "28 giờ trước",
        text: "Một cuốn sách rất hay và bổ ích cho các em nhỏ. Hình ảnh rất đẹp và sinh động, nội dung ý nghĩa.",
        reply: { user: "Trả lời", time: "24 giờ trước", text: "" }
      }
    ]
  },
  {
    id: 2,
    title: "Miền cỏ hát",
    subtitle: "",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: true,
    price: null,
    rating: 4.3,
    views: 18540,
    editions: 89,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "14x20 cm",
    bookType: "Sách ebook",
    pages: 156,
    language: "Tiếng Việt",
    isbn: "978-604-1-12345-6",
    maISBN: "",
    coverColor: "#C5D8A0",
    description: "Tuyển tập truyện thiếu nhi về miền quê yên bình với những cánh đồng cỏ xanh mướt.",
    chapters: ["Phần 1", "Phần 2", "Phần 3"],
    comments: []
  },
  {
    id: 3,
    title: "Bầu trời trong quả trứng",
    subtitle: "",
    author: "Xuân Quỳnh",
    authorBooks: 22,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.8,
    views: 42100,
    editions: 205,
    categories: ["Sách Thiếu nhi", "Thơ"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2018,
    size: "13x19 cm",
    bookType: "Sách giấy, ebook",
    pages: 128,
    language: "Tiếng Việt",
    isbn: "978-604-2-23456-7",
    maISBN: "",
    coverColor: "#F0D5A0",
    description: "Tập thơ thiếu nhi kinh điển của nhà thơ Xuân Quỳnh, với những bài thơ trong trẻo, giàu hình ảnh.",
    chapters: ["Bài 1", "Bài 2", "Bài 3"],
    comments: []
  },
  {
    id: 4,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.6,
    views: 25300,
    editions: 134,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 198,
    language: "Tiếng Việt",
    isbn: "978-604-0-67890-1",
    maISBN: "",
    coverColor: "#D0E8F0",
    description: "Câu chuyện phiêu lưu kỳ thú của Ốc Tiêu trong thế giới thần tiên.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  },
  {
    id: 5,
    title: "Rung cảm đầu đời (tặng 2 tấm thiệp)",
    subtitle: "",
    author: "Nguyễn Nhật Ánh",
    authorBooks: 48,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.9,
    views: 56700,
    editions: 310,
    categories: ["Văn học thiếu nhi"],
    genre: "Văn học thiếu nhi",
    yearPublished: 2021,
    size: "13x20 cm",
    bookType: "Sách giấy, ebook",
    pages: 246,
    language: "Tiếng Việt",
    isbn: "978-604-3-45678-9",
    maISBN: "",
    coverColor: "#F5C0C0",
    description: "Tác phẩm mới nhất của Nguyễn Nhật Ánh về những rung cảm tuổi mới lớn.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4", "Chương 5", "Chương 6"],
    comments: []
  },
  {
    id: 6,
    title: "Làm chủ cơn giận",
    subtitle: "Subtitle title",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "311.500đ / Tháng",
    rating: 4.2,
    views: 53158,
    editions: 3039,
    categories: ["Sách Thiếu nhi", "Minh hoạ", "Truyện tranh"],
    genre: "Tác phẩm kinh điển",
    yearPublished: 2019,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook, xã hội hoá",
    pages: 212,
    language: "Tiếng Việt",
    isbn: "978-604-0-58012-6",
    maISBN: "970-604-02-58012-6",
    coverColor: "#FFE0B0",
    description: `Cuốn sách giúp trẻ em hiểu và kiểm soát cảm xúc giận dữ. Thông qua những câu chuyện sinh động và hình ảnh minh hoạ đẹp mắt, cuốn sách dạy trẻ cách nhận biết khi nào mình đang tức giận, tại sao mình tức giận và làm thế nào để xử lý cảm xúc đó một cách tích cực.

Mỗi chương sách đều có bài tập thực hành để trẻ có thể áp dụng ngay vào cuộc sống hàng ngày. Đây là cuốn sách không thể thiếu trong tủ sách của mọi gia đình có con nhỏ.

Sách cũng bao gồm phần hướng dẫn dành cho phụ huynh, giúp cha mẹ hiểu và đồng hành cùng con trong việc quản lý cảm xúc.`,
    chapters: ["Chương 1: Cơn giận là gì?", "Chương 2: Nhận biết cảm xúc", "Chương 3: Kỹ thuật hít thở", "Chương 4: Nói ra nỗi lòng", "Chương 5: Bài tập vui"],
    comments: [
      {
        user: "Thành Luân",
        badge: "CÁN BỘ CNTT",
        time: "28 giờ trước",
        text: "Sách rất hữu ích cho việc giáo dục cảm xúc trẻ em. Hình ảnh đẹp, nội dung phù hợp lứa tuổi.",
        reply: null
      }
    ]
  },
  {
    id: 7,
    title: "Chìm ra rừng hành hạnh phúc",
    subtitle: "",
    author: "Hoàng Liên",
    authorBooks: 8,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "250.000đ / Tháng",
    rating: 4.1,
    views: 12400,
    editions: 67,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "15x21 cm",
    bookType: "Sách ebook",
    pages: 180,
    language: "Tiếng Việt",
    isbn: "978-604-4-56789-0",
    maISBN: "",
    coverColor: "#D8F0D0",
    description: "Hành trình tìm kiếm hạnh phúc trong khu rừng kỳ diệu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3"],
    comments: []
  },
  {
    id: 8,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu (Tập 2)",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.7,
    views: 21000,
    editions: 98,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 210,
    language: "Tiếng Việt",
    isbn: "978-604-0-78901-2",
    maISBN: "",
    coverColor: "#E0D0F0",
    description: "Phần tiếp theo của cuộc phiêu lưu Ốc Tiêu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3"],
    comments: []
  },
  {
    id: 9,
    title: "Làm chủ con giận (tặng 2 tấm thiệp)...",
    subtitle: "",
    author: "Phạm Hồn Cơ",
    authorBooks: 15,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "195.000đ / Tháng",
    rating: 4.0,
    views: 8900,
    editions: 45,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2021,
    size: "14x20 cm",
    bookType: "Sách ebook",
    pages: 144,
    language: "Tiếng Việt",
    isbn: "978-604-5-89012-3",
    maISBN: "",
    coverColor: "#F0E0C0",
    description: "Tuyển tập bài tập quản lý cảm xúc cho trẻ em.",
    chapters: ["Phần 1", "Phần 2", "Phần 3"],
    comments: []
  },
  {
    id: 10,
    title: "Tủ sách Tuổi Thần tiên - Thiên thần Ốc Tiêu (Tập 3)",
    subtitle: "",
    author: "Elizabeth Gele",
    authorBooks: 29,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: true,
    price: null,
    rating: 4.5,
    views: 19500,
    editions: 87,
    categories: ["Sách Thiếu nhi", "Truyện tranh"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2021,
    size: "17x24 cm",
    bookType: "Sách giấy, ebook",
    pages: 195,
    language: "Tiếng Việt",
    isbn: "978-604-0-99123-4",
    maISBN: "",
    coverColor: "#C0E0F0",
    description: "Tập 3 của series Thiên thần Ốc Tiêu.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  },
  {
    id: 11,
    title: "Bầu trời trong quả trứng (Bản Audio)",
    subtitle: "",
    author: "Xuân Quỳnh",
    authorBooks: 22,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Audio",
    isVip: true,
    price: null,
    rating: 4.6,
    views: 15600,
    editions: 78,
    categories: ["Sách Thiếu nhi"],
    genre: "Sách Thiếu nhi",
    yearPublished: 2020,
    size: "",
    bookType: "Audiobook",
    pages: 0,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    description: "Phiên bản audio của tập thơ Bầu trời trong quả trứng.",
    chapters: [],
    comments: []
  },
  {
    id: 12,
    title: "Rung cảm đầu đời (tặng 2 tấm thiệp) Tập 2...",
    subtitle: "",
    author: "Nguyễn Nhật Ánh",
    authorBooks: 48,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "280.000đ / Tháng",
    rating: 4.4,
    views: 31200,
    editions: 156,
    categories: ["Văn học thiếu nhi"],
    genre: "Văn học thiếu nhi",
    yearPublished: 2022,
    size: "13x20 cm",
    bookType: "Sách giấy, ebook",
    pages: 268,
    language: "Tiếng Việt",
    isbn: "978-604-3-56789-0",
    maISBN: "",
    coverColor: "#E8C0D0",
    description: "Phần tiếp theo của Rung cảm đầu đời.",
    chapters: ["Chương 1", "Chương 2", "Chương 3", "Chương 4"],
    comments: []
  },
  {
    id: 13,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành tiếp diễn (Past Perfect Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1205,
    editions: 10,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/26/image-20260326114914102.png",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 14,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành tiếp diễn (Future Perfect Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1540,
    editions: 12,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325090916895.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 15,
    title: "Kiến thức Tiếng Anh trọng tâm: Danh từ đếm được, Danh từ không đếm được (Countable Nouns & Uncountable Nouns)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.8,
    views: 3200,
    editions: 34,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325082812609.png",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 16,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai gần (Near Future Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.2,
    views: 900,
    editions: 8,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 100,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162808613.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 17,
    title: "Kiến thức Tiếng Anh trọng tâm Động từ nguyên mẫu (To verb)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1100,
    editions: 9,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 110,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162838695.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 18,
    title: "Toán tư duy tiền tiểu học",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5600,
    editions: 120,
    categories: ["Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "20x20 cm",
    bookType: "Ebook",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319120355074.jpg",
    description: "Giúp trẻ phát triển tư duy từ sớm.",
    chapters: [],
    comments: []
  },
  {
    id: 19,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại hoàn thành (Present Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.7,
    views: 4500,
    editions: 42,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 160,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316123652646.png",
    description: "Tài liệu ôn luyện chuyên sâu.",
    chapters: [],
    comments: []
  },
  {
    id: 20,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành (Future Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.3,
    views: 1250,
    editions: 14,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 115,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316153417345.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 21,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành (Past Perfect Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1800,
    editions: 18,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 125,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/13/image-20260313162537925.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 22,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai đơn (Simple Future Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.8,
    views: 5400,
    editions: 60,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 140,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/10/image-20260310151314926.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 23,
    title: "Kiến thức Tiếng Anh trọng tâm: Tương lai tiếp diễn (Future Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.1,
    views: 750,
    editions: 5,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 105,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/7/image-20260307100233319.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 24,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ tiếp diễn (Past Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.6,
    views: 3100,
    editions: 28,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306083737170.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 25,
    title: "Kiến thức Tiếng Anh trọng tâm: Quá khứ đơn (Past Simple Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "20.000 đ",
    rating: 4.9,
    views: 8200,
    editions: 95,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 160,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306085422183.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 26,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại tiếp diễn (Present Continuous Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 4500,
    editions: 33,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 135,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306141601047.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 27,
    title: "Kiến thức Tiếng Anh trọng tâm: Hiện tại đơn (Present Simple Tense)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 12000,
    editions: 154,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/3/5/image-20260305102435472.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 28,
    title: "Cuộc phiêu lưu của chú Kiến Vàng",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "10.455 đ",
    rating: 4.7,
    views: 3100,
    editions: 26,
    categories: ["Sách Thiếu nhi"],
    genre: "Truyện tranh",
    yearPublished: 2026,
    size: "15x21 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227144734328.jpg",
    description: "Truyện kể cho bé.",
    chapters: [],
    comments: []
  },
  {
    id: 29,
    title: "Kiến thức Tiếng Anh trọng tâm: Tính từ miêu tả (Descriptive Adjective)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.3,
    views: 1800,
    editions: 15,
    categories: ["Sách tham khảo", "Giáo dục"],
    genre: "Sách tham khảo",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 110,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227091856276.jpg",
    description: "Tài liệu học tập chi tiết.",
    chapters: [],
    comments: []
  },
  {
    id: 30,
    title: "Cẩm nang ôn thi tốt nghiệp tin học, chuyên đề về website HTML (tập 1)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 2900,
    editions: 31,
    categories: ["Sách tham khảo", "Giáo dục", "Công nghệ thông tin"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 200,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090637354.png",
    description: "Tài liệu chuyên sâu ngành lập trình web.",
    chapters: [],
    comments: []
  },
  {
    id: 31,
    title: "Cẩm nang ôn thi tốt nghiệp tin học chuyên đề về Website: CSS (tập 1)",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3300,
    editions: 38,
    categories: ["Sách tham khảo", "Giáo dục", "Công nghệ thông tin"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2026,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 220,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090956096.png",
    description: "Tài liệu chuyên môn hữu ích.",
    chapters: [],
    comments: []
  },
  {
    id: 32,
    title: "Những vĩ nhân trong lịch sử: Ernest Hemingway",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 15400,
    editions: 205,
    categories: ["Tiểu sử - Hồi ký"],
    genre: "Kiến thức chung",
    yearPublished: 2025,
    size: "13x20 cm",
    bookType: "Ebook",
    pages: 350,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/11/27/image-book-20251127081656947.png",
    description: "Câu chuyện về cuộc đời của nhà văn vĩ đại.",
    chapters: [],
    comments: []
  },
  {
    id: 33,
    title: "Phương tiện giao thông quanh ta",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 1250,
    editions: 15,
    categories: ["Sách thiếu nhi", "Giáo dục"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/11/image-book-20250811140652361.jpg",
    description: "Sách giúp bé tìm hiểu phương tiện giao thông.",
    chapters: [],
    comments: []
  },
  {
    id: 34,
    title: "Việt Nam muôn màu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 3400,
    editions: 22,
    categories: ["Sách thiếu nhi", "Văn hóa"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 60,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100405005.jpg",
    description: "Giới thiệu văn hóa Việt Nam.",
    chapters: [],
    comments: []
  },
  {
    id: 35,
    title: "Nghề nghiệp tương lai: Logistics - cung ứng",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 1800,
    editions: 12,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094800703.jpg",
    description: "Tìm hiểu ngành logistics.",
    chapters: [],
    comments: []
  },
  {
    id: 36,
    title: "Nghề nghiệp tương lai: Du lịch",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 2200,
    editions: 18,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094442151.jpg",
    description: "Tìm hiểu ngành du lịch.",
    chapters: [],
    comments: []
  },
  {
    id: 37,
    title: "Nghề nghiệp tương lai: Tài nguyên môi trường",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.4,
    views: 1500,
    editions: 10,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095249548.jpg",
    description: "Tìm hiểu ngành môi trường.",
    chapters: [],
    comments: []
  },
  {
    id: 38,
    title: "Tết thiếu nhi",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5600,
    editions: 40,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 40,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095939163.jpg",
    description: "Khám phá tết thiếu nhi.",
    chapters: [],
    comments: []
  },
  {
    id: 39,
    title: "Nghề nghiệp tương lai: Nông nghiệp công nghệ cao",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.5,
    views: 1300,
    editions: 11,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-2025070409491636.jpg",
    description: "Tìm hiểu ngành nông nghiệp CNC.",
    chapters: [],
    comments: []
  },
  {
    id: 40,
    title: "Tết Trung thu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 6500,
    editions: 45,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 45,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100127787.jpg",
    description: "Khám phá trăng rằm.",
    chapters: [],
    comments: []
  },
  {
    id: 41,
    title: "Khám phá Quốc kì",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 3100,
    editions: 20,
    categories: ["Giáo dục"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 60,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704093255109.jpg",
    description: "Nhận biết cờ các nước.",
    chapters: [],
    comments: []
  },
  {
    id: 42,
    title: "Nghề nghiệp tương lai: Phân tích dữ liệu",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 4500,
    editions: 33,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Hướng nghiệp",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 100,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095029845.jpg",
    description: "Tìm hiểu ngành Data.",
    chapters: [],
    comments: []
  },
  {
    id: 43,
    title: "Tết Nguyên đán",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 8000,
    editions: 55,
    categories: ["Sách thiếu nhi"],
    genre: "Sách thiếu nhi",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 50,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E8D4A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095744719.jpg",
    description: "Khám phá tết cổ truyền.",
    chapters: [],
    comments: []
  },
  {
    id: 44,
    title: "Lạc quanh thế giới: Lạc khám phá Nam Mỹ bí ẩn",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4100,
    editions: 22,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C5D8A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/8/8/image-book-20250808083006201.png",
    description: "Hành trình đến Nam Mỹ.",
    chapters: [],
    comments: []
  },
  {
    id: 45,
    title: "Lạc quanh thế giới: Lạc tới Thổ Nhĩ Kỳ cổ kính",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 3200,
    editions: 18,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0D5A0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320100948394.png",
    description: "Khám phá vùng đất giao thoa.",
    chapters: [],
    comments: []
  },
  {
    id: 46,
    title: "Lạc quanh thế giới: Lạc tới New Zealand và Australia",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3800,
    editions: 21,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D0E8F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101301424.png",
    description: "Khám phá châu Đại Dương.",
    chapters: [],
    comments: []
  },
  {
    id: 47,
    title: "Lạc quanh thế giới: Lạc tới nước Ý mộng mơ",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.9,
    views: 5200,
    editions: 30,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F5C0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-2025032009163242.png",
    description: "Lang thang ở kinh đô nghệ thuật.",
    chapters: [],
    comments: []
  },
  {
    id: 48,
    title: "Lạc quanh thế giới: Lạc vào Ai Cập huyền bí",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4700,
    editions: 25,
    categories: ["Khám phá", "Văn hóa"],
    genre: "Du ký",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 120,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#FFE0B0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101739797.png",
    description: "Bí ẩn lăng mộ Pharaoh.",
    chapters: [],
    comments: []
  },
  {
    id: 49,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Ai là người phát hiện ra tia X",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.6,
    views: 2900,
    editions: 14,
    categories: ["Khoa học"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#D8F0D0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317142940692.png",
    description: "Khám phá khoa học quanh ta.",
    chapters: [],
    comments: []
  },
  {
    id: 50,
    title: "Tìm hiểu các trường Đại học ở Việt Nam: Đại học Bách khoa Hà Nội",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 7500,
    editions: 60,
    categories: ["Giáo dục", "Hướng nghiệp"],
    genre: "Tài liệu chuyên ngành",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 150,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#E0D0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/5/12/image-book-20250512094945531.png",
    description: "Tài liệu luyện thi và tìm hiểu.",
    chapters: [],
    comments: []
  },
  {
    id: 51,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Chiếc máy ảnh đầu tiên trên thế giới ra đời như thế nào?",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.7,
    views: 3100,
    editions: 19,
    categories: ["Khoa học"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 80,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#F0E0C0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317140914719.png",
    description: "Lịch sử công nghệ.",
    chapters: [],
    comments: []
  },
  {
    id: 52,
    title: "Có thể bạn chưa biết: Kiến thức hay về khoa học kỹ thuật! Tàu Parker và hành trình vượt không gian khám phá vũ trụ",
    subtitle: "",
    author: "Nhiều Tác Giả",
    authorBooks: 0,
    publisher: "Benito",
    publisherFull: "CP Văn hoá và Bản quyền Benito",
    type: "Ebook",
    isVip: false,
    price: "5.000 đ",
    rating: 4.8,
    views: 4200,
    editions: 25,
    categories: ["Khoa học", "Vũ trụ"],
    genre: "Kiến thức",
    yearPublished: 2025,
    size: "17x24 cm",
    bookType: "Ebook",
    pages: 90,
    language: "Tiếng Việt",
    isbn: "",
    maISBN: "",
    coverColor: "#C0E0F0",
    coverImage: "https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317133017076.png",
    description: "Hành trình ra ngoài không gian.",
    chapters: [],
    comments: []
  }
];

// Categories for sidebar
const CATEGORIES = [
  {
    title: "DANH MỤC SÁCH CỦA BẠN",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  },
  {
    title: "PHÂN LOẠI THEO BỘ SÁCH",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  }
];

const TOPICS = [
  "Truyện cổ tích",
  "Tác phẩm kinh điển",
  "Văn học thiếu nhi",
  "Truyện tranh Nhật Bản",
  "Chăm sóc sức khoẻ trẻ em",
  "Kinh tế - Chính trị - Xã hội",
  "Tâm lý học"
];

const AUTHORS_LIST = [
  "Nguyễn Nhật Ánh",
  "Phan Thị Vàng Anh",
  "Trần Tùng Chinh",
  "Nguyễn Văn Anh",
  "Hoàng Liên",
  "Xuân Quỳnh",
  "Nguyễn Mỹ Nữ"
];

const LANGUAGES = ["Tiếng Việt", "Tiếng Anh", "Tiếng Trung"];
